name: build-website

on:
  workflow_call:

jobs:
  build-application:
    name: Build application
    runs-on: ubuntu-latest

    services:
      sql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: Y

    steps:
    - uses: actions/checkout@v2

    - name: Install .NET
      uses: actions/setup-dotnet@v1

    - name: Restore website
      run: |
        dotnet restore

    - name: Build website
      run: |
        dotnet build --no-restore --configuration Release

    - name: Test website
      run: |
        dotnet test --no-build --no-restore --configuration Release --filter "FullyQualifiedName!~AcceptanceTests"
      env:
        ConnectionStrings__DefaultConnection: Server=.;Database=CleanArchitectureBlazorDb-Test;User=sa;Password=Your_password123;MultipleActiveResultSets=true;Encrypt=false;

    - name: Publish website
      run: |
        dotnet publish --no-build --no-restore --configuration Release --output ./publish
      working-directory: ./src/WebUI/Server
    
    - name: Zip website
      run: |
        zip -r ./publish.zip .
      working-directory: ./src/WebUI/Server/publish

    - name: Upload website as workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: ./src/WebUI/Server/publish/publish.zip
        if-no-files-found: error
